import { HTTP_STATUS, type HttpStatus } from './http.constants.ts';

export const DOMAIN_ERROR_STATUS_MAP: Record<string, HttpStatus> = {
	PLAN_NOT_FOUND: HTTP_STATUS.NOT_FOUND,
	PAYMENT_ORDER_NOT_FOUND: HTTP_STATUS.NOT_FOUND,
	RESOURCE_NOT_FOUND: HTTP_STATUS.NOT_FOUND,
	ACTIVE_SUBSCRIPTION_EXISTS: HTTP_STATUS.CONFLICT,
	PAYMENT_ALREADY_PROCESSED: HTTP_STATUS.CONFLICT,
	CONFLICT: HTTP_STATUS.CONFLICT,
	UNAUTHORIZED_RESTAURANT: HTTP_STATUS.UNAUTHORIZED,
	UNAUTHORIZED: HTTP_STATUS.UNAUTHORIZED,
	INVALID_PAYMENT_SIGNATURE: HTTP_STATUS.BAD_REQUEST,
	BAD_REQUEST: HTTP_STATUS.BAD_REQUEST,
};

export function getStatusCodeForDomainError(
	code: string,
	fallback: HttpStatus = HTTP_STATUS.INTERNAL_SERVER_ERROR,
): HttpStatus {
	return DOMAIN_ERROR_STATUS_MAP[code] || fallback;
}
