export enum HttpStatusCode {
	OK = 200,
	CREATED = 201,
	ACCEPTED = 202,
	NO_CONTENT = 204,
	NOT_MODIFIED = 304,
	BAD_REQUEST = 400,
	UNAUTHORIZED = 401,
	FORBIDDEN = 403,
	NOT_FOUND = 404,
	METHOD_NOT_ALLOWED = 405,
	CONFLICT = 409,
	UNPROCESSABLE_ENTITY = 422,
	INTERNAL_SERVER_ERROR = 500,
	BAD_GATEWAY = 502,
	SERVICE_UNAVAILABLE = 503,
	GATEWAY_TIMEOUT = 504,
}

export const HTTP_STATUS = {
	OK: HttpStatusCode.OK,
	CREATED: HttpStatusCode.CREATED,
	ACCEPTED: HttpStatusCode.ACCEPTED,
	NO_CONTENT: HttpStatusCode.NO_CONTENT,
	NOT_MODIFIED: HttpStatusCode.NOT_MODIFIED,
	BAD_REQUEST: HttpStatusCode.BAD_REQUEST,
	UNAUTHORIZED: HttpStatusCode.UNAUTHORIZED,
	FORBIDDEN: HttpStatusCode.FORBIDDEN,
	NOT_FOUND: HttpStatusCode.NOT_FOUND,
	METHOD_NOT_ALLOWED: HttpStatusCode.METHOD_NOT_ALLOWED,
	CONFLICT: HttpStatusCode.CONFLICT,
	UNPROCESSABLE_ENTITY: HttpStatusCode.UNPROCESSABLE_ENTITY,
	INTERNAL_SERVER_ERROR: HttpStatusCode.INTERNAL_SERVER_ERROR,
	BAD_GATEWAY: HttpStatusCode.BAD_GATEWAY,
	SERVICE_UNAVAILABLE: HttpStatusCode.SERVICE_UNAVAILABLE,
	GATEWAY_TIMEOUT: HttpStatusCode.GATEWAY_TIMEOUT,
} as const;

export type HttpStatus = (typeof HTTP_STATUS)[keyof typeof HTTP_STATUS];
