export const MESSAGES = {
	NOT_FOUND: 'Not Found',
	INTERNAL_SERVER_ERROR: 'Internal Server Error',
	UNEXPECTED_ERROR: 'An unexpected error occurred',
	UNHANDLED_ERROR: 'Unhandled error occurred',
	INCOMING_REQUEST: 'Incoming request',
	REQUEST_COMPLETED: 'Request completed',
	REDIS_CONNECTING: 'Connecting to Redis...',
	REDIS_CONNECTED: 'Redis connected',
	REDIS_READY: 'Redis ready to accept commands',
	REDIS_RECONNECTING: 'Redis reconnecting...',
	REDIS_DISCONNECTING: 'Disconnecting Redis client...',
	REDIS_DISCONNECTED: 'Redis disconnected',
	REDIS_RECONNECT_FAILED: 'Redis reconnect failed',
	REDIS_ERROR: 'Redis Error:',
	DATABASE_DISCONNECTING: 'Disconnecting database client...',
	DATABASE_DISCONNECTED: 'Database client disconnected',
	BULLMQ_CONNECTED: 'BullMQ Connected',
	BULLMQ_DISCONNECTED: 'BullMQ Disconnected',
	BULLMQ_CONNECTION_ERROR: 'BullMQ Redis Connection Error',
	BULLMQ_CONNECTION_FAILED: 'BullMQ Connection Failed',
	BULLMQ_DISCONNECT_ERROR: 'BullMQ Disconnect Error',
	BULLMQ_INIT_FAILED: 'Failed to initialize BullMQ infrastructure. Shutting down...',
	RAZORPAY_INITIALIZED: 'Razorpay Initialized',
	RAZORPAY_INIT_FAILED: 'Failed to initialize Razorpay infrastructure. Shutting down...',
	RAZORPAY_INITIALIZATION_FAILED: 'Razorpay Initialization Failed',
	RAZORPAY_CONFIG_MISSING:
		'Razorpay configuration missing: RAZORPAY_TEST_API_KEY or RAZORPAY_TEST_SECRET_KEY is not defined',
	RAZORPAY_CREDS_EMPTY: 'Razorpay credentials cannot be empty',
	SHUTDOWN_SIGINT: 'Received SIGINT. Gracefully shutting down...',
	SHUTDOWN_SIGTERM: 'Received SIGTERM. Gracefully shutting down...',
	SHUTDOWN_IN_PROGRESS: 'Received shutdown signal but shutdown is already in progress...',
	SHUTDOWN_COMPLETED: 'Graceful shutdown completed',
	SHUTDOWN_STARTING: 'Gracefully shutting down...',
	SERVER_BOOTSTRAP_FAILED: 'Failed to bootstrap server',
} as const;

export type Message = (typeof MESSAGES)[keyof typeof MESSAGES];
