export enum MessageEnum {
	NOT_FOUND = 'Not Found',
	INTERNAL_SERVER_ERROR = 'Internal Server Error',
	UNEXPECTED_ERROR = 'An unexpected error occurred',
	UNHANDLED_ERROR = 'Unhandled error occurred',
	INCOMING_REQUEST = 'Incoming request',
	REQUEST_COMPLETED = 'Request completed',
	REDIS_CONNECTING = 'Connecting to Redis...',
	REDIS_CONNECTED = 'Redis connected',
	REDIS_READY = 'Redis ready to accept commands',
	REDIS_RECONNECTING = 'Redis reconnecting...',
	REDIS_DISCONNECTING = 'Disconnecting Redis client...',
	REDIS_DISCONNECTED = 'Redis disconnected',
	REDIS_RECONNECT_FAILED = 'Redis reconnect failed',
	REDIS_ERROR = 'Redis Error:',
	DATABASE_DISCONNECTING = 'Disconnecting database client...',
	DATABASE_DISCONNECTED = 'Database client disconnected',
	BULLMQ_CONNECTED = 'BullMQ Connected',
	BULLMQ_DISCONNECTED = 'BullMQ Disconnected',
	BULLMQ_CONNECTION_ERROR = 'BullMQ Redis Connection Error',
	BULLMQ_CONNECTION_FAILED = 'BullMQ Connection Failed',
	BULLMQ_DISCONNECT_ERROR = 'BullMQ Disconnect Error',
	BULLMQ_INIT_FAILED = 'Failed to initialize BullMQ infrastructure. Shutting down...',
	RAZORPAY_INITIALIZED = 'Razorpay Initialized',
	RAZORPAY_INIT_FAILED = 'Failed to initialize Razorpay infrastructure. Shutting down...',
	RAZORPAY_INITIALIZATION_FAILED = 'Razorpay Initialization Failed',
	RAZORPAY_CONFIG_MISSING = 'Razorpay configuration missing: RAZORPAY_TEST_API_KEY or RAZORPAY_TEST_SECRET_KEY is not defined',
	RAZORPAY_CREDS_EMPTY = 'Razorpay credentials cannot be empty',
	SHUTDOWN_SIGINT = 'Received SIGINT. Gracefully shutting down...',
	SHUTDOWN_SIGTERM = 'Received SIGTERM. Gracefully shutting down...',
	SHUTDOWN_IN_PROGRESS = 'Received shutdown signal but shutdown is already in progress...',
	SHUTDOWN_COMPLETED = 'Graceful shutdown completed',
	SHUTDOWN_STARTING = 'Gracefully shutting down...',
	SERVER_BOOTSTRAP_FAILED = 'Failed to bootstrap server',

	// Subscription & Payment Operation Messages
	SUBSCRIPTION_PLANS_FETCHED = 'Subscription plans fetched successfully',
	SUBSCRIPTION_ORDER_CREATED = 'Subscription order created successfully',
	PAYMENT_VERIFIED_SUCCESS = 'Payment verified and subscription activated successfully',
	SUBSCRIPTION_STATUS_FETCHED = 'Subscription status retrieved successfully',
	PLAN_NOT_FOUND = 'Subscription plan not found',
	ACTIVE_SUBSCRIPTION_EXISTS = 'Restaurant already has an active subscription',
	PAYMENT_ORDER_NOT_FOUND = 'Payment order not found',
	INVALID_PAYMENT_SIGNATURE = 'Invalid payment signature provided',
	PAYMENT_ALREADY_PROCESSED = 'Payment has already been processed',
	UNAUTHORIZED_RESTAURANT = 'Unauthorized or missing restaurant identification',
	VALIDATION_ERROR = 'Invalid request parameters',
}

export const MESSAGES = {
	NOT_FOUND: MessageEnum.NOT_FOUND,
	INTERNAL_SERVER_ERROR: MessageEnum.INTERNAL_SERVER_ERROR,
	UNEXPECTED_ERROR: MessageEnum.UNEXPECTED_ERROR,
	UNHANDLED_ERROR: MessageEnum.UNHANDLED_ERROR,
	INCOMING_REQUEST: MessageEnum.INCOMING_REQUEST,
	REQUEST_COMPLETED: MessageEnum.REQUEST_COMPLETED,
	REDIS_CONNECTING: MessageEnum.REDIS_CONNECTING,
	REDIS_CONNECTED: MessageEnum.REDIS_CONNECTED,
	REDIS_READY: MessageEnum.REDIS_READY,
	REDIS_RECONNECTING: MessageEnum.REDIS_RECONNECTING,
	REDIS_DISCONNECTING: MessageEnum.REDIS_DISCONNECTING,
	REDIS_DISCONNECTED: MessageEnum.REDIS_DISCONNECTED,
	REDIS_RECONNECT_FAILED: MessageEnum.REDIS_RECONNECT_FAILED,
	REDIS_ERROR: MessageEnum.REDIS_ERROR,
	DATABASE_DISCONNECTING: MessageEnum.DATABASE_DISCONNECTING,
	DATABASE_DISCONNECTED: MessageEnum.DATABASE_DISCONNECTED,
	BULLMQ_CONNECTED: MessageEnum.BULLMQ_CONNECTED,
	BULLMQ_DISCONNECTED: MessageEnum.BULLMQ_DISCONNECTED,
	BULLMQ_CONNECTION_ERROR: MessageEnum.BULLMQ_CONNECTION_ERROR,
	BULLMQ_CONNECTION_FAILED: MessageEnum.BULLMQ_CONNECTION_FAILED,
	BULLMQ_DISCONNECT_ERROR: MessageEnum.BULLMQ_DISCONNECT_ERROR,
	BULLMQ_INIT_FAILED: MessageEnum.BULLMQ_INIT_FAILED,
	RAZORPAY_INITIALIZED: MessageEnum.RAZORPAY_INITIALIZED,
	RAZORPAY_INIT_FAILED: MessageEnum.RAZORPAY_INIT_FAILED,
	RAZORPAY_INITIALIZATION_FAILED: MessageEnum.RAZORPAY_INITIALIZATION_FAILED,
	RAZORPAY_CONFIG_MISSING: MessageEnum.RAZORPAY_CONFIG_MISSING,
	RAZORPAY_CREDS_EMPTY: MessageEnum.RAZORPAY_CREDS_EMPTY,
	SHUTDOWN_SIGINT: MessageEnum.SHUTDOWN_SIGINT,
	SHUTDOWN_SIGTERM: MessageEnum.SHUTDOWN_SIGTERM,
	SHUTDOWN_IN_PROGRESS: MessageEnum.SHUTDOWN_IN_PROGRESS,
	SHUTDOWN_COMPLETED: MessageEnum.SHUTDOWN_COMPLETED,
	SHUTDOWN_STARTING: MessageEnum.SHUTDOWN_STARTING,
	SERVER_BOOTSTRAP_FAILED: MessageEnum.SERVER_BOOTSTRAP_FAILED,

	// Subscription & Payment Operation Messages
	SUBSCRIPTION_PLANS_FETCHED: MessageEnum.SUBSCRIPTION_PLANS_FETCHED,
	SUBSCRIPTION_ORDER_CREATED: MessageEnum.SUBSCRIPTION_ORDER_CREATED,
	PAYMENT_VERIFIED_SUCCESS: MessageEnum.PAYMENT_VERIFIED_SUCCESS,
	SUBSCRIPTION_STATUS_FETCHED: MessageEnum.SUBSCRIPTION_STATUS_FETCHED,
	PLAN_NOT_FOUND: MessageEnum.PLAN_NOT_FOUND,
	ACTIVE_SUBSCRIPTION_EXISTS: MessageEnum.ACTIVE_SUBSCRIPTION_EXISTS,
	PAYMENT_ORDER_NOT_FOUND: MessageEnum.PAYMENT_ORDER_NOT_FOUND,
	INVALID_PAYMENT_SIGNATURE: MessageEnum.INVALID_PAYMENT_SIGNATURE,
	PAYMENT_ALREADY_PROCESSED: MessageEnum.PAYMENT_ALREADY_PROCESSED,
	UNAUTHORIZED_RESTAURANT: MessageEnum.UNAUTHORIZED_RESTAURANT,
	VALIDATION_ERROR: MessageEnum.VALIDATION_ERROR,
} as const;

export type Message = (typeof MESSAGES)[keyof typeof MESSAGES];
